language: ruby
sudo: false
cache: bundler
rvm:
- 1.9.3
env:
  global:
    - GOVUK_APP_DOMAIN: dev
    - DEV_DOMAIN: dev
    - JUVIA_BASE_URL: https://juvia.example.com
    - QUIRKAFLEEG_DAPAAS_JUVIA_SITE_KEY: abc123
    - QUIRKAFLEEG_DAPAAS_SESSION_SECRET: abc123
